[tools]
pre-commit = "latest"
python = "3.14"
trivy = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'cicd-workflow'
GITOPS_REPO = 'cicd-workflow-gitops'

[hooks]
enter = "bash ./scripts/setup_project"
