#!/usr/bin/env bash
set -euo pipefail

if ! command -v cz >/dev/null && [ "${DEVPOD:-}" = "true" ]; then
  git config --global push.autoSetupRemote true
  git config --global --add safe.directory /workspaces/cicd-workflow
  pip install --user pipx
  pipx install commitizen
  pre-commit install
  pre-commit install --hook-type commit-msg
fi
